# Generated by Django 4.2.4 on 2023-10-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0005_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default=1, upload_to='avatares'),
            preserve_default=False,
        ),
    ]
